# Generated by Django 4.0.1 on 2022-02-07 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loadImage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageload',
            old_name='edite',
            new_name='edited',
        ),
    ]
