# Generated by Django 4.0.1 on 2022-03-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='url_img',
            field=models.ImageField(null=True, upload_to='img_profile/'),
        ),
    ]
